### PR TITLE
Neox

### PR DESCRIPTION
**Pull request by zhangir-azerbayev**
Adding the neox v1 source code to our repository. 

Because we (a) need to use neox v1 and not neox v2, since only v1 is compatible with pythia checkpoints, and (b) we need to make changes to the v1 source code, I think that having initializing a copy of the v1 source in this repo is the best way forward.

### CODE REVIEW

**Review by haileyschoelkopf — APPROVED** [review]
LGTM if this is how we want to organize it--doing a git submodule and maintaining a `math-lm` branch within the gpt-neox repository might be smoother though? But no strong preference.

**Comment by zhangir-azerbayev** [comment]
The advantage of the submodule approach would be that we could merge in new PRs to v2 that are useful to us more easily. Are the v1 and v2 sources similar enough that this will be useful? 

We should also add Sean's fork of the eval harness as a git submodule. I'll open a PR for that.

**Comment by zhangir-azerbayev** [comment]
> LGTM if this is how we want to organize it--doing a git submodule and maintaining a `math-lm` branch within the gpt-neox repository might be smoother though? But no strong preference.

**Comment by haileyschoelkopf** [comment]
Yup, at its core the original code change from v1.0 -> v2.0 in the neox repo is not large, just a few minor changes to make module names compatible with upstream DeepSpeed.

I believe @honglu2875 just converted some Pythia checkpoints to v2.0 using https://github.com/EleutherAI/gpt-neox/pull/836 and I can also handle this if it'll allow us to use any extra features in v2.0 / will add convenience!

**Comment by zhangir-azerbayev** [comment]
It seems like a good idea to keep the project synchronized with the latest version of NeoX. I'll go ahead and add NeoX 2.0 as a submodule in a new branch and PR (so that we have a cleaner git history).

**Pull request closed without merging**
